const $=s=>document.querySelector(s);let source=null,result=null;
const ids=['brightness','contrast','saturation','hue','blur','sharpen','colors','detail','area','smooth','feature'];
const readSettings=()=>({brightness:+$('#brightness').value,contrast:+$('#contrast').value,saturation:+$('#saturation').value,hue:+$('#hue').value,blur:+$('#blur').value,sharpen:+$('#sharpen').value,colors:+$('#colors').value,detail:+$('#detail').value,area:+$('#area').value,smooth:+$('#smooth').value,printer:$('#printer').checked,outWidth:+$('#outWidth').value,outHeightMode:$('#outHeightMode').value});
function updateLabels(){ids.forEach(id=>{const e=$('#'+id),o=$('#'+id+'Out');if(!e||!o)return;o.textContent=e.value+(id==='hue'?'°':id==='detail'?'%':id==='area'?' px':id==='feature'?' mm':'')});}
function drawPreview(){if(!source)return;const c=$('#previewCanvas'),ctx=c.getContext('2d');const max=900,s=Math.min(1,max/source.width,max/source.height);c.width=Math.round(source.width*s);c.height=Math.round(source.height*s);const off=VF.process(source,readSettings()).canvas;ctx.drawImage(off,0,0,c.width,c.height)}
function loadFile(file){if(!file||!file.type.startsWith('image/'))return;const img=new Image();img.onload=()=>{source=img;$('#fileName').textContent=file.name;$('#fileName').removeAttribute('data-i18n');$('#dimensions').textContent=`${img.naturalWidth} × ${img.naturalHeight}`;$('#empty').style.display='none';$('#convert').disabled=false;drawPreview()};img.src=URL.createObjectURL(file)}
async function doConvert(){if(!source)return;$('#progress').classList.add('active');const settings=readSettings();result=await convertImage(source,settings,p=>$('#progress span').style.width=p+'%');$('#download').disabled=false;renderColors(result.palette);setTimeout(()=>$('#progress').classList.remove('active'),400)}
function renderColors(palette){$('#colorList').innerHTML=palette.map(c=>`<div class="swatch" style="background:${VF.hex(c.r,c.g,c.b)}"><span>${VF.hex(c.r,c.g,c.b)}</span></div>`).join('')}
function downloadResult(){if(!result)return;const fmt=$('#format').value;let blob,name;if(fmt==='svg'){blob=new Blob([result.svg],{type:'image/svg+xml'});name='vectorforge.svg'}else if(fmt==='png'){blob=new Promise(r=>{const a=document.createElement('canvas');a.width=result.canvas.width;a.height=result.canvas.height;a.getContext('2d').drawImage(result.canvas,0,0);a.toBlob(r,'image/png')});blob.then(b=>save(b,'vectorforge.png'));return}else{blob=new Blob([JSON.stringify({colors:result.palette.map(c=>VF.hex(c.r,c.g,c.b))},null,2)],{type:'application/json'});name='vectorforge-colors.json'}save(blob,name)}
function save(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#fileInput').addEventListener('change',e=>loadFile(e.target.files[0]));['dragenter','dragover'].forEach(x=>$('#dropZone').addEventListener(x,e=>{e.preventDefault();$('#dropZone').classList.add('drag')}));['dragleave','drop'].forEach(x=>$('#dropZone').addEventListener(x,e=>{e.preventDefault();$('#dropZone').classList.remove('drag')}));$('#dropZone').addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
ids.forEach(id=>$('#'+id)?.addEventListener('input',()=>{updateLabels();drawPreview()}));$('#convert').addEventListener('click',doConvert);$('#download').addEventListener('click',downloadResult);$('#format').addEventListener('change',()=>{const svg=$('#format').value==='svg';$('#printer').disabled=!svg;if(!svg){$('#printer').checked=false;$('#printerOptions').classList.add('hidden')} });$('#printer').addEventListener('change',e=>$('#printerOptions').classList.toggle('hidden',!e.target.checked));updateLabels();
